Issue/437/magnification bias
LSSTDESC/CLMM pull request #438
Opened 2021-10-01 16:30 UTC by marina-ricci

2021-11-04 15:45 UTC, marina-ricci commented
This should be done now.

2021-11-04 15:46 UTC, marina-ricci commented on clmm/theory/generic.py
> +        magnification)**(np.array([alpha]).T - 1)
Ok, it should be done now.

2021-11-04 16:16 UTC, m-aguena requested changes
Can you make sure the lines are shorter than 100 characters? You can check in the files you changed with the command `grep -x '.\{100,\}' my_file.py`

2021-11-04 16:16 UTC, m-aguena commented on clmm/theory/func_layer.py
> +from . generic import *
please do not import `*`

2021-11-04 16:16 UTC, m-aguena commented on clmm/theory/generic.py
> +            Shear
there is an extra tab here

2021-11-04 16:16 UTC, m-aguena commented on clmm/theory/generic.py
> +            Shear
also on lines 23 and 28

2021-11-04 16:16 UTC, m-aguena commented on clmm/theory/parent_class.py
> +
extra tab

2021-11-04 16:16 UTC, m-aguena commented on clmm/theory/parent_class.py
> +    def eval_magnification_bias(self, r_proj, z_cl, z_src, alpha):
can you add an validation function? just follow the model of `eval_magnification`

2021-11-04 16:16 UTC, m-aguena commented on clmm/theory/parent_class.py
> +from .generic import *
please do not import `*`

2021-11-12 15:08 UTC, marina-ricci commented
@m-aguena , I think it should be good now!

2021-11-19 15:41 UTC, m-aguena approved these changes

2021-11-19 15:41 UTC, m-aguena approved these changes
@marina-ricci it looks good for me now.
I would just like @combet to have a final look before merging as I made a couple of changes.

2021-11-19 15:47 UTC, marina-ricci commented
@hsinfan1996  Please be careful because the checks are failing since your commit.

2021-11-19 15:49 UTC, hsinfan1996 commented
> @hsinfan1996 Please be careful because the checks are failing since your commit.

I noticed, but I really don't think the check failures were related to my commit.

2021-11-19 15:55 UTC, combet commented
The error appears when installing CLMM during CI (that's a new one...)

error: numpy 1.17.4 is installed but numpy>=1.18 is required by {'astropy'}
Error: Process completed with exit code 1.

2021-11-19 15:56 UTC, hsinfan1996 commented
@m-aguena astropy 5.0 is installed during `install prereq using pip`. Too new.

2021-11-19 16:00 UTC, hsinfan1996 commented
Need to edit requirements.txt.

2021-11-19 16:46 UTC, combet approved these changes
Thank you, all looks good!

2021-11-19 17:29 UTC, merged