Issue/552/improve 2h functions
LSSTDESC/CLMM pull request #575
Opened 2023-03-07 13:24 UTC by rancesol

- Improve efficiency of the `*_2h` functions by replacing `interp1d` with `splev` and `splrep`.
- Changed previously hard coded values in the `*_2h` functions into optional user defined arguments.
- Added shape requirement to the validate_argument function in clmm/utils.py.

2023-03-17 17:33 UTC, m-aguena commented
@rancesol the changes look good, it's just missing a unit test for the new functionality you added to validate_argument. Can you add it to `tests/test_utils.py`? Thanks

2023-03-22 18:39 UTC, m-aguena requested changes
https://github.com/LSSTDESC/CLMM/pull/575#issuecomment-1474180580

2023-03-24 13:05 UTC, m-aguena requested changes

2023-03-24 13:05 UTC, m-aguena commented on tests/test_utils.py
Hi @rancesol , what you also want here is to make sure the `validate_argument` raises an error when the shape is wrong. Try using a `assert_raises` test

2023-04-14 14:00 UTC, marina-ricci approved these changes
Thank you @rancesol for these changes! It looks good to me.

2023-04-14 18:08 UTC, merged