Issue/592/ccl v3
LSSTDESC/CLMM pull request #595
Opened 2023-05-05 19:45 UTC by hsinfan1996

2023-05-05 19:50 UTC, hsinfan1996 commented on clmm/theory/ccl_v3.py
> +        return self.hdpm._get_alpha(self.cosmo.be_cosmo, self.__mdelta_cor, a_cl)
This line is different from that of v2. In v3 `self.mdef` is not needed for `_get_alpha`.

2023-05-05 19:59 UTC, hsinfan1996 commented
If we are not supporting both v2 and v3 at the same time, I will delete this PR as this is not necessary. However, we will need to update README to specify the maximum or minimum version of CCL supported.

2023-05-06 12:07 UTC, m-aguena commented
I don't think it will be feasible to maintain support for both versions. We should just keep track which releases are currently supported.

2023-05-12 08:12 UTC, hsinfan1996 commented
- [ ] Update _ccl_supported_versions, README and INSTALL accordingly after merging main

2023-06-13 18:08 UTC, hsinfan1996 commented
Don't know if anyone is using CCL v2.8, but this PR is for them and is ready. We can still wait for the official release of CCL v3.

2023-06-28 10:15 UTC, m-aguena commented
@hsinfan1996 do you know if there is an ETA for CCL v3?

2023-06-28 10:44 UTC, hsinfan1996 commented
> @hsinfan1996 do you know if there is an ETA for CCL v3?

I think there is no exact date for the release of CCL v3. What I know is that before the official release of v3, there are still some tweaks needed on documentation and example notebooks, which can be found here https://github.com/LSSTDESC/CCL/milestone/5.

2023-08-04 13:55 UTC, hsinfan1996 commented
CCL v3 will be tagged on Monday.

2023-08-18 14:35 UTC, m-aguena commented
@hsinfan1996 when you were talking about removing `virial` mass from cluster_toolkit, you meant line 88 of `clmm/theory/cluster_toolkit.py`?

2023-08-18 14:38 UTC, hsinfan1996 commented
> @hsinfan1996 when you were talking about removing `virial` mass from cluster_toolkit, you meant line 88 of `clmm/theory/cluster_toolkit.py`?

Yes. I added that line so it was consistent with CCL backend at that time.

2023-08-18 15:02 UTC, m-aguena commented
> > @hsinfan1996 when you were talking about removing `virial` mass from cluster_toolkit, you meant line 88 of `clmm/theory/cluster_toolkit.py`?
> 
> Yes. I added that line so it was consistent with CCL backend at that time.

I see, so it can be removed now. Just remember to also update the docstring of `CTCLMModeling`

2023-08-25 14:37 UTC, m-aguena requested changes
I think it would be a good idea to add `use_projected_quad` in the `theory.func_layer` functions. Also add examples in notebooks

2023-08-25 14:37 UTC, m-aguena commented on clmm/theory/parent_class.py
> +    def set_projected_quad(self, projected_quad):
can you change `projected_quad` to something like `use_projected_quad`?
Also do this for `_set_projected_quad` functions

2023-09-07 10:13 UTC, m-aguena requested changes
There are a few notebooks that are failing due CCL v3.0 API changes, can you update them?
```
Paper_v1.0/mcmc.ipynb
Paper_v1.0/validation_tests.ipynb
Paper_v1.0/mass_bias_from_models.ipynb
other_compare_NFW_critical_massdef.ipynb
```
Thanks

2023-09-07 10:41 UTC, hsinfan1996 commented
> There are a few notebooks that are failing due CCL v3.0 API changes, can you update them?
> 
> ```
> 
> Paper_v1.0/mcmc.ipynb
> 
> Paper_v1.0/validation_tests.ipynb
> 
> Paper_v1.0/mass_bias_from_models.ipynb
> 
> other_compare_NFW_critical_massdef.ipynb
> 
> ```
> 
> Thanks 

Yes, will do. I thought they should be in the state as when the paper was published for archival purposes.

2023-09-07 11:35 UTC, m-aguena commented
> > There are a few notebooks that are failing due CCL v3.0 API changes, can you update them?
> > ```
> > 
> > Paper_v1.0/mcmc.ipynb
> > 
> > Paper_v1.0/validation_tests.ipynb
> > 
> > Paper_v1.0/mass_bias_from_models.ipynb
> > 
> > other_compare_NFW_critical_massdef.ipynb
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Thanks
> 
> Yes, will do. I thought they should be in the state as when the paper was published for archival purposes.

That version will still be able to be accessed by going to CLMM v1.0

2023-09-07 15:32 UTC, hsinfan1996 commented
Don't know how to update "examples/Paper_v1.0/mcmc.ipynb". Maybe leave it to issue #606.

2023-09-15 13:56 UTC, m-aguena commented
> Don't know how to update "examples/Paper_v1.0/mcmc.ipynb". Maybe leave it to issue #606 since it is related to NumCosmo.

You are right, this is related to NumCosmo

2023-09-15 14:04 UTC, m-aguena approved these changes

2023-09-15 16:10 UTC, hsinfan1996 commented
Forcing cmake=3.27.4 makes checks run again, but makes solving environment very slow. Want to wait a little longer to see if everything fixes itself again.

2023-09-15 18:30 UTC, hsinfan1996 commented
Fixed GH Actions by adding `--override-channels` when installing cmake.

2023-09-17 06:13 UTC, hsinfan1996 commented
Not sure why, maybe related to the release of cmake 3.27.5, conda cannot solve the environment consistently and get package from conda-forge if `--override-channels` is not issued.

2023-09-17 12:33 UTC, hsinfan1996 commented
Only cmake from conda-forge works regardless of the versions.

2023-09-17 16:30 UTC, hsinfan1996 commented
On a side note, numpy 1.26 is compatible.

2023-09-18 09:31 UTC, m-aguena commented
> Not sure why, maybe related to the release of cmake 3.27.5, conda cannot solve the environment consistently and get all packages from conda-forge if `--override-channels` is not issued. On my computer, issuing `conda install -c conda-forge cmake swig` can get different results. Most notably, `swig` may be installed from conda or conda-forge every time I issue the same command.

This will do for now. We can keep an issue to see if it will be solved by a newer version of conda

2023-09-18 09:35 UTC, merged