feat: Add coordinate_system parameter to compute_tangential_and_cross_components and _compute_lensing_angles functions
LSSTDESC/CLMM pull request #624
Opened 2024-07-15 09:15 UTC by caioolivv

Add option to choose coordinate system of ellipticity components.

2024-07-16 13:32 UTC, caioolivv commented
@marina-ricci hey, I think the PR is ready for a review!

2024-07-16 13:59 UTC, hsinfan1996 commented on clmm/dataops/__init__.py
> +        phi = np.pi - phi
`phi = np.arctan2(deltay, deltax)` should do the work. (note: for coordinate_system == "pixel", the calculation is `phi = np.arctan2(deltay, -deltax)`)

2024-07-16 15:09 UTC, caioolivv commented
Since @hsinfan1996 mentioned that it was better to keep things consistent between _compute_lensing_angles_flatsky and _compute_lensing_angles_astropy, it may be better to revert the last commit.

2024-07-16 15:15 UTC, hsinfan1996 commented
> Since @hsinfan1996 mentioned that it was better to keep things consistent between _compute_lensing_angles_flatsky and _compute_lensing_angles_astropy, it may be better to revert the last commit.

Yeah, I am sorry. I was thinking that the calculation would be easier by flipping the sign of `deltax` for the falt-sky version. However, we only use the astropy version right now, so it may be better to keep the calculations consistent. i will let other reviewers to decide which practice is better.

2024-07-17 13:23 UTC, marina-ricci commented
I asked @caioolivv to change the notebooks and add an example in the mock_data notebook for the two definitions. @caioolivv let me know when the PR is ready for review !

2024-07-17 13:26 UTC, caioolivv commented
Everything's ready @marina-ricci !

2024-07-17 14:28 UTC, marina-ricci requested changes
Thank you @caioolivv for this important PR! Since the coordinate system is an important but often missed subtlety, we should clearly highlight it. Hence I suggest : 
- to add a references ( like papers) for the definitions in the code (in comments) and in the notebooks ;
- to highlights the differences between the cordinate systyems and profiles in `demo_dataops_functionality.ipynb`
- to expand also the `demo_mock_cluster.ipynb` notebook.

2024-07-17 14:28 UTC, marina-ricci commented on clmm/galaxycluster.py
> +    coordinate_system : str
You have to specify which one is the default value.

2024-07-17 14:28 UTC, marina-ricci commented on clmm/support/mock_data.py
> +    coordinate_system : str, optional
same here, specify the default  value

2024-07-17 14:28 UTC, marina-ricci commented on clmm/support/mock_data.py
> +    coordinate_system : str, optional
Also, could you add a reference for these definitions? Like a paper?

2024-07-18 10:07 UTC, caioolivv commented
Ready for review @marina-ricci

2024-07-18 10:45 UTC, marina-ricci commented
@caioolivv I think there is  a typo in `demo_dataops_functionality` notebook that is breaking the code. "coordinate system"=piru

2024-07-18 10:49 UTC, caioolivv commented
Sorry @marina-ricci , was testing the paramenter validation and forgot to go back to the original value.

2024-07-18 13:36 UTC, marina-ricci commented
Ok, everything seems good now !

2024-07-18 13:45 UTC, marina-ricci approved these changes
It lokks good thank you Caio!!!!

2024-07-18 13:48 UTC, merged