Issue/401/use qp+fix zinteg
LSSTDESC/CLMM pull request #644
Opened 2024-09-26 15:14 UTC by m-aguena

Closes #401 and #643

2024-09-29 14:08 UTC, hsinfan1996 reviewed
1. Should we add `qp` to `requirements.txt` and the Requirements section in `README`?

2. It seems to me that the imports in some of the files are not compliant with PEP8, but since `pylint` doesn't complain about C0411 / wrong-import-order, it is not a big deal. I am just wondering.

2024-09-30 07:49 UTC, combet commented on examples/test_pz_integral.ipynb
This new notebook is very useful to see the various behaviors, but the markdown text needs to be corrected/expanded to help the user understand better what is happening. At the moment, the markdown seems to copied/pasted from another demo notebook and gives little information as to what is actually happening.

2024-09-30 08:29 UTC, combet commented on examples/test_pz_integral.ipynb
Would be good to add a legend in the figure comparing the pdz computed for the 3 types (individual, shared and quantiles)

2024-09-30 08:56 UTC, combet requested changes
Thank you @m-aguena. It's great to see qp and the quantile option available! 

I've tested the code and everything appears to be working well. I just have comments about the new notebook showing the integral with qp versus clmm, etc. At the moment, I don't think they are enough or clear enough markdown explanations to easily understand what this is doing.

2024-09-30 08:56 UTC, combet commented on examples/test_pz_integral.ipynb
Also, maybe add some explanation text for the last figure of the notebook. I find trick to understand what is actually shown.

2024-09-30 08:56 UTC, combet commented on examples/test_pz_integral.ipynb
And why is the qp integral performing worse than the clmm-implemented ones but for the "quantiles" case where qp appears to perform better?

2024-09-30 14:11 UTC, m-aguena commented on examples/test_pz_integral.ipynb
I added more explanation to the notebook

2024-09-30 14:15 UTC, m-aguena commented on examples/test_pz_integral.ipynb
I think that `qp` is performing worse than `clmm` because it kind of used a type like integral with the precision set by the separation of the zbins of the input provided, and in `clmm` we are refining the grid for the integral.

In the case of using quantiles, I think `qp` might be outperforming `clmm` because it is actually using the statistical meaning of quantiles while `clmm` recreates an interpolated PDF and integrates it, thus loosing information.

2024-09-30 14:21 UTC, m-aguena commented on clmm/gcdata.py
> +                out += " - upacked with zgrid : " + str(
Thanks @hsinfan1996 ! I could not figure out how to add `qp` properly to `requirements.txt`. You're welcome to give it a try

2024-09-30 15:20 UTC, hsinfan1996 commented
I added qp (`qp-prob`) to both `requirements.txt` and `environment.yml`. It would be great if some conda users can check if `environment.yml` works.

2024-10-01 04:41 UTC, hsinfan1996 commented on INSTALL.md
> +    git clone https://github.com/LSSTDESC/qp.git; cd qp; python setup.py install; cd - # Install qp package
Issuing `python setup.py install` is deprecated. Maybe we can change this part to `pip install git+https://github.com/LSSTDESC/qp.git` for those who don't want to clone the repo.

2024-10-02 07:13 UTC, hsinfan1996 approved these changes

2024-10-02 08:34 UTC, combet approved these changes
Thanks for adding more explanations to the notebook. All looks good to me know!

2024-10-07 10:51 UTC, merged