Making CLMM conda instalable
LSSTDESC/CLMM pull request #651
Opened 2024-11-15 10:18 UTC by eduardojsbarroso

Changed the `pyproject.toml` file so we can publish CLMM to conda and pipy.

2024-11-15 10:25 UTC, eduardojsbarroso commented
Hi @m-aguena and @marina-ricci . As we discussed in the last pipeline meeting, indeed `pip install git+https://github.com/LSSTDESC/CLMM.git@1.14.1 ` works for CLMM. However I created a new `pyproject.toml` file and I was able to publish clmm to the `PypiTest`. I can also publish to `Pypi` and `Conda` now. However I would like your aproval. Also, should I publish or one of you guys? Since it will be associated with my account?

2024-11-15 15:34 UTC, marina-ricci commented
@eduardojsbarroso Michel and I are not familiar with what you proposed. Could you ellaborate?

2024-11-18 11:04 UTC, eduardojsbarroso commented
> @eduardojsbarroso Michel and I are not familiar with what you proposed. Could you ellaborate?

What I am proposing is that we publish the clmm git repository to Pipy and conda, so one can simply do `pip install clmm` or `conda install clmm`. To so, we need a `pyproject.toml` file with all the requirements, dependencies and licenses of the repository. After making this file, we can use `setuptools` I guess or another program to build the files that will be posted in `Pypi` and `conda` (I used a program called hatch). Then, after having all the files, we just need to publish them to `Pipy` and `conda`. However, you need to have an account at `Pipy` to publish. I created one, and published `clmm` in `PipyTest`, which is just to see if everything is working. Now I can publish to `Pipy` and `conda`, but then the package will be associated to my account, so I will be the one to update it when something changes. I can do that no problem, but if you guys prefer to do it since the repository is not mine, feel free to do it. Otherwise I can do it this week. I just noted that there was some problem with the new `pyproject.toml` file in the test

2024-11-19 16:19 UTC, m-aguena commented
@eduardojsbarroso I talked to the CCL people, and they said an account for the code was created. So, I will make the same for CLMM and give you access.

2024-11-20 15:17 UTC, m-aguena commented
@eduardojsbarroso can you add instructions on how to create these installation to the `Creating installation via pip and conda` section of `CONTRIBUTING.md`? Thanks

2024-11-23 03:40 UTC, hsinfan1996 commented
Since this PR touched upon the dependencies, can we check if astropy v7.0.0 is compatible, which was just released.

2024-11-24 09:00 UTC, hsinfan1996 commented
> Since this PR touched upon the dependencies, can we check if astropy v7.0.0 is compatible, which was just released.

Never mind. It is compatible.

2024-11-24 09:20 UTC, eduardojsbarroso commented
> > Since this PR touched upon the dependencies, can we check if astropy v7.0.0 is compatible, which was just released.
> 
> Never mind. It is compatible.

2024-11-24 12:27 UTC, eduardojsbarroso commented
Thank you for checking @hsinfan1996 . @m-aguena I just updated the documentation and published the version on [Pipy](https://pypi.org/project/clmm/) .  I also created the pull request for [Conda](https://github.com/conda-forge/staged-recipes/pull/28338)

2024-11-25 12:50 UTC, eduardojsbarroso commented
The package is now in the [conda-forge](https://anaconda.org/conda-forge/clmm) repository

2024-12-11 20:22 UTC, marina-ricci commented
Is there a way to update automatically the version stored in conda-forge and pypi? If we have to manually change the CLMM version to match the one in main it will be complicated.

2024-12-12 08:50 UTC, eduardojsbarroso commented
> Is there a way to update automatically the version stored in conda-forge and pypi? If we have to manually change the CLMM version to match the one in main it will be complicated.

I did some research and I think we can do this with Github Action, so whenever we have a new release, it will run the Github Action and publish to `Pipy`. I need to check if this also runs for small patch updates or only for a new release.

[Github Action1](https://python.plainenglish.io/automatic-versioning-and-release-python-package-ba15dfb8adf0)

[Github Action2](https://jacobtomlinson.dev/posts/2021/automating-releases-of-python-packages-with-github-actions/)

[Github Action3](https://www.ianwootten.co.uk/2020/10/23/publishing-to-pypi-using-github-actions/)


A couple points:
-  I think for this to happen, the setup files I have on this branch (`setup.py`, `pyproject.toml`) must be on the master branch. I propose I create a new Pull request from the master branch where I only change these two files and the Instalation documentation, since now we can use conda for CLMM, so we can set it up automatically with GitHub action.
- If you do not want to change these files on the main branch, I can just go on master, create a new branch from it, and publish it locally with the (`setup.py`, `pyproject.toml`) files from the `conda_instal` branch.

2025-11-25 11:28 UTC, caioolivv commented
Documentation breaks because CCL's mock version in `docs/conf.py` is set to 3:
```
sys.modules["pyccl"].__version__ = "3"
```
We're forced to do this because of the hard version check on CCL. Now we can either update this line every time we change version checks, or we remove the hard version check. I think the hard version check is unnecessary.

2025-12-04 10:29 UTC, m-aguena requested changes
@caioolivv it all looks pretty well (and clean!), thanks! I just left a comment to make sure the documentation reflects the current implementation

2025-12-04 10:29 UTC, m-aguena commented on CONTRIBUTING.md
> +## Creating installation via pip and conda <a name="creating_pip_conda"></a>
@caioolivv are these instructions still relevant? Isn't the build done by the CI right now?
If that is the case, we might still want to have them here in case it has to be done manually, but also add instructions on using the CI

2025-12-04 10:41 UTC, caioolivv commented on CONTRIBUTING.md
> +## Creating installation via pip and conda <a name="creating_pip_conda"></a>
Just added a small paragraph showing the process of publishing through the CI and edited a bit of the manual instructions.

2025-12-04 11:44 UTC, m-aguena approved these changes
@caioolivv thanks for all the work!

2025-12-04 14:39 UTC, merged